sonar.projectKey=scanner-app
sonar.projectName=Scanner App
sonar.sources=backend
sonar.host.url=http://localhost:9000
sonar.login=YOUR_TOKEN

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
